<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="adabot">


     <!--
         Properties for the robot bodies
    -->
    <xacro:property name="PI" value="3.1415926535897931 "/>
    <xacro:property name="SCALE" value="4" />

    <!-- Typical density of plastics -->
    <xacro:property name="mat_density" value="1000.0" />

    <!-- Chassis parameters -->
    <xacro:property name="ch_density_factor" value="0.4" />
    <xacro:property name="ch_density" value="${mat_density * ch_density_factor}" />
    <xacro:property name="ch_length"  value="${0.100 * SCALE}" />
    <xacro:property name="ch_width"   value="${0.070 * SCALE}" />
    <xacro:property name="ch_height"  value="${0.025 * SCALE}" />
    <xacro:property name="ch_mass"    value="${ch_density * ch_length * ch_width * ch_height}" />

    <!-- Wheel parameters -->
    <xacro:property name="wh_density_factor" value="0.4" />
    <xacro:property name="wh_density" value="${mat_density * wh_density_factor}" />
    <xacro:property name="wh_radius"  value="${0.020 * SCALE}" />
    <xacro:property name="wh_length"  value="${0.005 * SCALE}" />
    <xacro:property name="wh_mass"    value="${wh_density * PI * (wh_radius**2) * wh_length}" />

    <!-- Vertical offset so that the robot starts above ground -->
    <xacro:property name="z_offset" value="${wh_radius * 10}" />

</robot>
